# Site settings
author: Dang Nguyen
title: Why I decided to learn Software Development
header-img: img/home-bg.png
email: danghwin@gmail.com
copyright_name: Dang Nguyen
description: > # this means to ignore newlines until "baseurl:"
  In the pursuit of challenges
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dangwin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
